MvcLibraryApp/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLibraryApp.Models.Entities;
using MvcLibraryApp.Repositories;
using MvcLibraryApp.ViewModels.Books;

namespace MvcLibraryApp.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class BooksController : Controller
    {
        private readonly BookRepository _bookRepository;

        public BooksController()
        {
            _bookRepository = new BookRepository();
        }

        [HttpGet]
        public IActionResult Index()
        {
           var books= _bookRepository.GetList();
            return View(books);
        }

        [HttpGet("[action]")]//Add sayfasını getirir.
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost("[action]")]//Kaydetme işlemini yapar.
        public IActionResult Add([FromForm] AddBookViewModel request)
        {
            Book book = new()
            {
                Name = request.Name,
                Author = request.Author,
                ReleaseDate = request.ReleaseDate
            };
            _bookRepository.Add(book);
            return RedirectToAction("Index");
            
        }
        [Route("delete/{Id}")]
        public IActionResult Delete([FromRoute] int id)
        {
            var book = _bookRepository.Get(id);
            _bookRepository.Delete(book);
            return RedirectToAction("Index");
        }

        [HttpGet("[action]/{id}")]
        public ActionResult Update([FromRoute] int id)
        {
            var data = _bookRepository.Get(id);
            UpdateBookViewModel model = new() {
            Id= id,
            Author = data.Author,
            ReleaseDate = data.ReleaseDate,
            Name = data.Name
            };
            return View(model);
        }


        [HttpPost("[action]/{id}")]
        public ActionResult Update([FromForm] UpdateBookViewModel viewModel)
        {
            Book book = new Book()
            {
                Id = viewModel.Id,
                Name = viewModel.Name,
                ReleaseDate = viewModel.ReleaseDate,
                Author = viewModel.Author,
                
            };
            _bookRepository.Update(book);
            return RedirectToAction("Index");
        }
    }
}

MvcLibraryApp/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLibraryApp.Models.Entities;
using MvcLibraryApp.Repositories;
using MvcLibraryApp.ViewModels.Courses;

namespace MvcLibraryApp.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class CoursesController : Controller
    {
        private readonly CourseRepository _courseRepository;
        public CoursesController()
        {
            _courseRepository = new CourseRepository();
        }
        public IActionResult Index()
        {
            var course = _courseRepository.GetList();
            return View(course);
        }


        [HttpGet("[action]")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost("[action]")]
        public IActionResult Add([FromForm] AddCourseViewModel model)
        {
            Course course = new()
            {
                LessonName = model.LessonName,
                LessonTime = model.LessonTime,
            };
            _courseRepository.Add(course);
            TempData["Message"] = "Record added successfully";
            return RedirectToAction("Index");
        }


        [Route("delete/{id}")]
        public IActionResult Delete([FromRoute]int id)
        {
            var data = _courseRepository.Get(id);
             _courseRepository.Delete(data);
            return RedirectToAction("Index");
        }


        [HttpGet("[action]/{id}")]
        public ActionResult Update([FromRoute] int id)
        {
            var data = _courseRepository.Get(id);
            UpdateCourseViewModel model = new()
            {
                Id = id,
                LessonName = data.LessonName,
                LessonTime = data.LessonTime,
            };
            return View(model);
        }

        [HttpPost("[action]/{id}")]
        public ActionResult Update([FromForm] UpdateCourseViewModel model)
        {
            Course course = new()
            {
                Id = model.Id,
                LessonName = model.LessonName,
                LessonTime = model.LessonTime,
            };
            _courseRepository.Updated(course);
            return RedirectToAction("Index");

        }
    }
}

MvcLibraryApp/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLibraryApp.Models.Entities;
using MvcLibraryApp.Repositories;
using MvcLibraryApp.ViewModels.Students;

namespace MvcLibraryApp.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class StudentsController : Controller
    {
        private readonly StudentRepository _studentRepository;
        public StudentsController()
        {
            _studentRepository = new StudentRepository();
        }
        public IActionResult Index()
        {
            var students = _studentRepository.GetList();
            return View(students);
        }

        [HttpGet("[action]")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost("[action]")]
        public IActionResult Add([FromForm] AddStudentViewModel request)
        {
            Student student = new()
            {
                Name = request.Name,
                LastName = request.LastName,
                Language = request.Language,
                Number = request.Number,
            };
            _studentRepository.Add(student);
            return RedirectToAction("Index");
        }
        [Route("delete/{id}")]
        public IActionResult Delete([FromRoute] int id)
        {
            var student = _studentRepository.Get(id);
            _studentRepository.Delete(student);
            return RedirectToAction("Index");
        }
        [HttpGet("[action]/{id}")]
        public ActionResult Update([FromRoute] int id)
        {
            var data = _studentRepository.Get(id);
            UpdateStudentViewModel model = new() //mapping
            {
                Id = id,
                Name = data.Name,
                LastName = data.LastName,
                Language = data.Language,
                Number = data.Number
            };
            return View(model);
        }
        [HttpPost("[action]/{id}")]
        public ActionResult Update([FromForm] UpdateStudentViewModel request)
        {
            Student student = new()
            {
                Id = request.Id,
                Name = request.Name,
                LastName = request.LastName,
                Language = request.Language,
                Number = request.Number,
            };
            _studentRepository.Update(student);
            return RedirectToAction("Index");
        }
    }
}

MvcLibraryApp/Controllers/TeachersController.cs
using Microsoft.AspNetCore.Mvc;
using MvcLibraryApp.Models.Entities;
using MvcLibraryApp.Repositories;
using MvcLibraryApp.ViewModels.Students;
using MvcLibraryApp.ViewModels.Teachers;

namespace MvcLibraryApp.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class TeachersController : Controller
    {
        private readonly TeacherRepository _teacherRepository;
        public TeachersController()
        {
            _teacherRepository = new TeacherRepository();
        }
        public IActionResult Index()
        {
            var teacher = _teacherRepository.GetList();
            return View(teacher);
        }

        [HttpGet("[action]")]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost("[action]")]
        public IActionResult Add([FromForm] AddTeacherViewModel request)
        {
            Teacher teacher = new()
            {
                Name = request.Name,
                LastName = request.LastName,
                ExperienceYear = request.ExperienceYear,
            };
            _teacherRepository.Add(teacher);
            return RedirectToAction("Index");
        }
        [Route("delete/{id}")]
        public IActionResult Delete([FromRoute] int id)
        {
            var teacher = _teacherRepository.Get(id);
            _teacherRepository.Delete(teacher);
            return RedirectToAction("Index");
        }
        [HttpGet("[action]/{id}")]
        public ActionResult Update([FromRoute] int id)
        {
            var data = _teacherRepository.Get(id);
            UpdateTeacherViewModel model = new() //mapping
            {
                Id = id,
                Name = data.Name,
                LastName = data.LastName,
                ExperienceYear = data.ExperienceYear
            };
            return View(model);
        }
        [HttpPost("[action]/{id}")]
        public ActionResult Update([FromForm] UpdateTeacherViewModel request)
        {
            Teacher teacher = new()
            {
                Id = request.Id,
                Name = request.Name,
                LastName = request.LastName,
                ExperienceYear = request.ExperienceYear,
            };
            _teacherRepository.Update(teacher);
            return RedirectToAction("Index");
        }

    }
}

MvcLibraryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcLibraryApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcLibraryApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcLibraryApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teachers" asp-action="Index">Teacher</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Course</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer mt-auto py-3" style="background-color:burlywood">
        <div class="container text-center">
            <span class="text-muted">© 2023 MvcLibraryApp. All rights reserved.</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>